# Generated by Django 3.1 on 2020-08-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=10)),
                ('AGE', models.IntegerField()),
                ('NUMBER', models.IntegerField()),
                ('DATE', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='All',
        ),
    ]
