# Generated by Django 3.1 on 2020-08-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20200813_0743'),
    ]

    operations = [
        migrations.CreateModel(
            name='All',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sale_id', models.CharField(max_length=10)),
                ('amount', models.IntegerField()),
                ('record_date', models.DateTimeField()),
                ('raw_record_date_formatted', models.DateTimeField()),
                ('Hour', models.IntegerField()),
                ('query_date', models.DateField()),
                ('server_date', models.DateTimeField()),
                ('account_reference', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('Weekday_Name', models.CharField(max_length=10)),
                ('subcounty_name', models.CharField(max_length=10)),
                ('part_id', models.IntegerField()),
                ('subpart_id', models.IntegerField()),
                ('transaction_mode_id', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Mass',
        ),
    ]
