# Generated by Django 3.1 on 2020-08-14 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_auto_20200813_0914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='all',
            old_name='raw_record_date_formatted',
            new_name='raw_recorded_date_formatted',
        ),
    ]
