# Generated by Django 3.1 on 2020-08-17 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_auto_20200815_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all',
            name='Hour',
        ),
        migrations.RemoveField(
            model_name='all',
            name='Weekday_Name',
        ),
        migrations.RemoveField(
            model_name='all',
            name='subcounty_name',
        ),
    ]
