# Generated by Django 3.1 on 2020-08-17 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_auto_20200817_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all',
            name='raw_recorded_date_formatted',
        ),
    ]
