# Generated by Django 3.1 on 2020-08-18 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0009_auto_20200817_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='all',
            name='query_date',
        ),
        migrations.RemoveField(
            model_name='all',
            name='server_date',
        ),
    ]
