# Generated by Django 3.1 on 2020-08-18 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0010_auto_20200818_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all',
            name='updated_at',
        ),
    ]
