# Generated by Django 3.1 on 2020-08-18 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0011_remove_all_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all',
            name='account_reference',
        ),
    ]
