# Generated by Django 3.1 on 2020-08-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0012_remove_all_account_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all',
            name='sale_id',
            field=models.CharField(max_length=20),
        ),
    ]
