# Generated by Django 3.1 on 2020-08-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0013_auto_20200819_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusiestHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hour', models.IntegerField()),
                ('Sub_name', models.CharField(max_length=20)),
            ],
        ),
    ]
