# Generated by Django 3.1 on 2020-08-20 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0014_busiesthour'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusiestHour',
        ),
    ]
